[package]
name = "transfer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
common.workspace = true
tokio.workspace = true
axum.workspace = true
axum-extra.workspace = true
tower-http.workspace = true
tracing.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
sqlx.workspace = true
hex.workspace = true
uuid.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
futures.workspace = true
tokio-util.workspace = true

reqwest.workspace = true
subtle.workspace = true
time.workspace = true

[dev-dependencies]
axum-test.workspace = true
serde_json.workspace = true
ring.workspace = true
