[package]
name = "ugh"
version = "0.1.0"
edition = "2021"
categories = ["caching"]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4"
bdays = "0.1"
cached = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
